# Generated by Django 4.2.26 on 2025-11-15 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان جایزه', max_length=200)),
                ('issuer', models.CharField(blank=True, help_text='مؤسسه اهداکننده', max_length=200, null=True)),
                ('rank', models.CharField(blank=True, help_text='رتبه', max_length=100, null=True)),
                ('date', models.CharField(blank=True, help_text='تاریخ', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='توضیح مختصر')),
                ('order', models.IntegerField(default=0, help_text='Order for sorting')),
            ],
            options={
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام دوره', max_length=200)),
                ('provider', models.CharField(blank=True, help_text='مؤسسه برگزارکننده', max_length=200, null=True)),
                ('instructor', models.CharField(blank=True, help_text='مدرس', max_length=200, null=True)),
                ('completion_date', models.CharField(blank=True, help_text='تاریخ اتمام', max_length=50, null=True)),
                ('duration', models.CharField(blank=True, help_text='مدت زمان', max_length=100, null=True)),
                ('certificate_id', models.CharField(blank=True, help_text='شماره گواهی', max_length=100, null=True)),
                ('verification_link', models.URLField(blank=True, help_text='لینک تأیید', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order for sorting')),
            ],
            options={
                'ordering': ['order', '-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='مقطع تحصیلی', max_length=100)),
                ('field', models.CharField(help_text='رشته/گرایش تحصیلی', max_length=200)),
                ('institution', models.CharField(help_text='نام دانشگاه/مؤسسه', max_length=200)),
                ('location', models.CharField(blank=True, help_text='شهر، کشور', max_length=200)),
                ('start_date', models.CharField(blank=True, help_text='تاریخ شروع', max_length=50)),
                ('end_date', models.CharField(blank=True, help_text="تاریخ پایان یا 'در حال تحصیل'", max_length=50)),
                ('gpa', models.CharField(blank=True, help_text='معدل و مقیاس', max_length=50, null=True)),
                ('honors', models.CharField(blank=True, help_text='رتبه/افتخارات', max_length=200, null=True)),
                ('thesis', models.CharField(blank=True, help_text='عنوان پایان\u200cنامه', max_length=500, null=True)),
                ('relevant_courses', models.JSONField(blank=True, default=list, help_text='دروس مرتبط')),
                ('order', models.IntegerField(default=0, help_text='Order for sorting')),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='نام زبان', max_length=100)),
                ('proficiency', models.CharField(blank=True, help_text='سطح تسلط کلی', max_length=50, null=True)),
                ('skills', models.JSONField(blank=True, default=dict, help_text='سطح گفتاری، نوشتاری، شنیداری، خواندن', null=True)),
                ('certificates', models.JSONField(blank=True, default=list, help_text='گواهینامه\u200cهای زبان')),
            ],
            options={
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام پروژه', max_length=200)),
                ('role', models.CharField(blank=True, help_text='نقش', max_length=200)),
                ('date', models.CharField(blank=True, help_text='تاریخ/مدت زمان', max_length=100)),
                ('technologies', models.JSONField(blank=True, default=list, help_text='تکنولوژی\u200cهای استفاده شده')),
                ('description', models.TextField(blank=True, help_text='توضیحات کامل')),
                ('link', models.URLField(blank=True, help_text='لینک پروژه', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order for sorting')),
            ],
            options={
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان مقاله', max_length=500)),
                ('authors', models.JSONField(blank=True, default=list, help_text='نویسندگان')),
                ('venue', models.CharField(blank=True, help_text='نام ژورنال/کنفرانس', max_length=200, null=True)),
                ('year', models.CharField(blank=True, help_text='سال انتشار', max_length=10, null=True)),
                ('volume_pages', models.CharField(blank=True, help_text='شماره مجلد/صفحات', max_length=100, null=True)),
                ('doi', models.CharField(blank=True, help_text='DOI', max_length=200, null=True)),
                ('link', models.URLField(blank=True, help_text='لینک', null=True)),
                ('citations', models.CharField(blank=True, help_text='تعداد ارجاعات', max_length=50, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order for sorting')),
            ],
            options={
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='SkillMentionedInJobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='دسته\u200cبندی مهارت (مثلاً: زبان\u200cهای برنامه\u200cنویسی، فریمورک\u200cها)', max_length=100)),
                ('name', models.CharField(help_text='نام مهارت', max_length=100)),
                ('level', models.CharField(blank=True, help_text='سطح تسلط (مثلاً: پیشرفته، متوسط)', max_length=50, null=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='parsedresume',
            options={'ordering': ['-parsed_at']},
        ),
        migrations.AddField(
            model_name='experience',
            name='company_type',
            field=models.CharField(blank=True, help_text='نوع شرکت', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='duration',
            field=models.CharField(blank=True, help_text='مدت زمان محاسبه شده', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(blank=True, help_text='نوع همکاری', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_currently_employed',
            field=models.BooleanField(default=False, help_text='آیا در حال حاضر مشغول به کار است'),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_title',
            field=models.CharField(blank=True, help_text='عنوان شغلی', max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, help_text='شهر، کشور', max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0, help_text='Order for sorting'),
        ),
        migrations.AddField(
            model_name='experience',
            name='reasoning',
            field=models.TextField(blank=True, help_text='توضیح کوتاه به فارسی'),
        ),
        migrations.AddField(
            model_name='experience',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list, help_text='شرح وظایف و دستاوردها'),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='extraction_notes',
            field=models.JSONField(blank=True, default=dict, help_text='Ambiguous items, missing sections, quality issues, special notes'),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='interests',
            field=models.JSONField(blank=True, default=dict, help_text='Professional, personal, volunteer interests and memberships'),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='military_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='other_links',
            field=models.JSONField(blank=True, default=list, help_text='List of other links'),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='other_sections',
            field=models.JSONField(blank=True, default=dict, help_text='Professional summary, career objectives, references, custom sections'),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(blank=True, help_text='نام شرکت/سازمان', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, help_text='Legacy: description field'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, help_text="تاریخ پایان یا 'تاکنون'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Legacy: is_current field'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='role',
            field=models.CharField(blank=True, help_text='Legacy: role field', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(blank=True, help_text='تاریخ شروع', max_length=50),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='parsed_data',
            field=models.JSONField(default=dict, help_text='Complete structured data from AI parsing (backup)'),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='raw_text',
            field=models.TextField(blank=True, help_text='Extracted raw text from CV file'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='technicalskill',
            name='parsed_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skills', to='candidates.parsedresume'),
        ),
        migrations.AddField(
            model_name='softskill',
            name='parsed_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_skills', to='candidates.parsedresume'),
        ),
        migrations.AddField(
            model_name='skillmentionedinjobtitle',
            name='parsed_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_mentioned_in_job_title', to='candidates.parsedresume'),
        ),
        migrations.AddField(
            model_name='publication',
            name='parsed_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='candidates.parsedresume'),
        ),
        migrations.AddField(
            model_name='project',
            name='parsed_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='candidates.parsedresume'),
        ),
        migrations.AddField(
            model_name='language',
            name='parsed_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='candidates.parsedresume'),
        ),
        migrations.AddField(
            model_name='education',
            name='parsed_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidates.parsedresume'),
        ),
        migrations.AddField(
            model_name='course',
            name='parsed_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='candidates.parsedresume'),
        ),
        migrations.AddField(
            model_name='award',
            name='parsed_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='candidates.parsedresume'),
        ),
        migrations.AlterUniqueTogether(
            name='technicalskill',
            unique_together={('parsed_resume', 'category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='softskill',
            unique_together={('parsed_resume', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='skillmentionedinjobtitle',
            unique_together={('parsed_resume', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('parsed_resume', 'language')},
        ),
    ]
