# Generated by Django 4.2.16 on 2025-11-15 16:55

import candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_award_course_education_language_project_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='relevant_courses',
            field=models.JSONField(blank=True, default=candidates.models.default_list, help_text='دروس مرتبط'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='responsibilities',
            field=models.JSONField(blank=True, default=candidates.models.default_list, help_text='شرح وظایف و دستاوردها'),
        ),
        migrations.AlterField(
            model_name='language',
            name='certificates',
            field=models.JSONField(blank=True, default=candidates.models.default_list, help_text='گواهینامه\u200cهای زبان'),
        ),
        migrations.AlterField(
            model_name='language',
            name='skills',
            field=models.JSONField(blank=True, default=candidates.models.default_dict, help_text='سطح گفتاری، نوشتاری، شنیداری، خواندن', null=True),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='extraction_notes',
            field=models.JSONField(blank=True, default=candidates.models.default_dict, help_text='Ambiguous items, missing sections, quality issues, special notes'),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='interests',
            field=models.JSONField(blank=True, default=candidates.models.default_dict, help_text='Professional, personal, volunteer interests and memberships'),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='other_links',
            field=models.JSONField(blank=True, default=candidates.models.default_list, help_text='List of other links'),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='other_sections',
            field=models.JSONField(blank=True, default=candidates.models.default_dict, help_text='Professional summary, career objectives, references, custom sections'),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='parsed_data',
            field=models.JSONField(default=candidates.models.default_dict, help_text='Complete structured data from AI parsing (backup)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.JSONField(blank=True, default=candidates.models.default_list, help_text='تکنولوژی\u200cهای استفاده شده'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.JSONField(blank=True, default=candidates.models.default_list, help_text='نویسندگان'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='metadata',
            field=models.JSONField(blank=True, default=candidates.models.default_dict),
        ),
    ]
