# Generated by Django 4.2.26 on 2025-11-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_add_ai_review_expected_salary_and_scoring_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobscore',
            name='score',
            field=models.FloatField(help_text='Overall score out of 100 (from scoring response)'),
        ),
    ]
