# Generated by Django 5.2.8 on 2025-11-17 10:28

import candidates.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_jobscore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='graduation_year',
            field=models.IntegerField(blank=True, help_text='Graduation year (numeric)', null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_category',
            field=models.CharField(blank=True, help_text='Institution category (e.g., Top Iranian Universities, International)', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='duration_months',
            field=models.IntegerField(blank=True, help_text='Duration in months (numeric)', null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='extracted_skills',
            field=models.JSONField(blank=True, default=candidates.models.default_list, help_text='Skills automatically extracted from responsibilities'),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='audit_trail',
            field=models.JSONField(blank=True, default=candidates.models.default_dict, help_text='Audit trail, completeness and assumptions'),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='education_level_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ELS summary score (0-100, 2 decimals)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='experience_depth_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='EDS summary score (0-100, 2 decimals)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='interpretation',
            field=models.JSONField(blank=True, default=candidates.models.default_dict, help_text='Interpretation and seniority fit analysis'),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='overall_weighted_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall weighted score (0-100, 2 decimals)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='scoring_details',
            field=models.JSONField(blank=True, default=candidates.models.default_dict, help_text='Full scoring_results.detailed_calculations payload'),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='seniority_match_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Seniority match score (0-100, 2 decimals)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.CharField(blank=True, help_text='Legacy duration text', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='category',
            field=models.CharField(blank=True, help_text='دسته\u200cبندی مهارت (مثلاً: زبان\u200cهای برنامه\u200cنویسی، فریمورک\u200cها)', max_length=100),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام گواهی', max_length=200)),
                ('issuer', models.CharField(blank=True, help_text='صادرکننده', max_length=200, null=True)),
                ('date', models.CharField(blank=True, help_text='تاریخ دریافت', max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='توضیحات یا مهارت\u200cهای پوشش داده شده')),
                ('certificate_id', models.CharField(blank=True, help_text='شماره گواهی', max_length=100, null=True)),
                ('verification_link', models.URLField(blank=True, help_text='لینک تأیید', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order for sorting')),
                ('parsed_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='candidates.parsedresume')),
            ],
            options={
                'ordering': ['order', '-date'],
            },
        ),
    ]
