# Generated by Django 5.2.8 on 2025-11-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_education_graduation_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='state',
            field=models.CharField(blank=True, choices=[('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offer_sent', 'Offer Sent'), ('hired', 'Hired')], default='shortlisted', help_text='Current state of the candidate in the hiring process', max_length=50),
        ),
    ]
