# Generated by Django 5.2.8 on 2025-11-19 01:00

import candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_fix_candidate_state_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedresume',
            name='raw_json_response',
            field=models.JSONField(blank=True, default=candidates.models.default_dict, help_text='Raw JSON response from AI before any processing (for debugging - admin only)'),
        ),
    ]
