# Generated by Django 4.2.16 on 2025-11-15 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_auto_reject_rules_and_more'),
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchupload',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if batch processing failed'),
        ),
        migrations.AddField(
            model_name='batchupload',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Job this batch is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_uploads', to='jobs.job'),
        ),
    ]
