# Generated by Django 4.2.26 on 2025-11-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='demographic_requirements',
            field=models.JSONField(blank=True, default=dict, help_text='Demographic requirements and auto-reject rules'),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], help_text='Type of employment', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Lead'), ('management', 'Management')], help_text='Required experience level', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_min_years',
            field=models.IntegerField(blank=True, help_text='Minimum years of experience required', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_min_years_auto_reject',
            field=models.BooleanField(default=False, help_text="Auto reject candidates who don't meet minimum years of experience"),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, help_text='e.g. Tehran, Remote', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='auto_reject_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Legacy: Rules for auto-rejecting candidates. Use demographic_requirements instead.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text="List of required skills with priority: [{'name': 'Python', 'priority': 'Critical'}, ...]"),
        ),
    ]
