# Generated by Django 4.2.26 on 2025-11-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_demographic_requirements_job_employment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='demographic_requirements',
        ),
        migrations.AddField(
            model_name='job',
            name='age_range_auto_reject',
            field=models.BooleanField(default=False, help_text='Auto reject candidates outside age range'),
        ),
        migrations.AddField(
            model_name='job',
            name='age_range_max',
            field=models.IntegerField(blank=True, help_text='Maximum age requirement', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='age_range_min',
            field=models.IntegerField(blank=True, help_text='Minimum age requirement', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's"), ('master', "Master's"), ('doctorate', 'Doctorate'), ('postdoctoral', 'Postdoctoral'), ('any', 'Any')], default='', help_text='Minimum educational level required', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='education_level_auto_reject',
            field=models.BooleanField(default=False, help_text="Auto reject if education level doesn't match"),
        ),
        migrations.AddField(
            model_name='job',
            name='education_major',
            field=models.JSONField(blank=True, default=list, help_text='List of required education majors'),
        ),
        migrations.AddField(
            model_name='job',
            name='education_major_auto_reject',
            field=models.BooleanField(default=False, help_text="Auto reject if education major doesn't match"),
        ),
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='', help_text='Gender requirement', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='gender_auto_reject',
            field=models.BooleanField(default=False, help_text="Auto reject if gender doesn't match"),
        ),
        migrations.AddField(
            model_name='job',
            name='military_auto_reject',
            field=models.BooleanField(default=False, help_text="Auto reject if military status doesn't match"),
        ),
        migrations.AddField(
            model_name='job',
            name='military_status',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('completed_or_full_exempt', 'Completed / Full Exempt'), ('educational_exempt', 'Educational Exempt'), ('any', 'Any')], default='', help_text='Military status requirement', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred_universities',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred university categories'),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred_universities_auto_reject',
            field=models.BooleanField(default=False, help_text="Auto reject if university doesn't match preferred categories"),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred_universities_enabled',
            field=models.BooleanField(default=False, help_text='Enable preferred universities filter'),
        ),
        migrations.AddField(
            model_name='job',
            name='target_companies',
            field=models.JSONField(blank=True, default=list, help_text='List of target company names'),
        ),
        migrations.AddField(
            model_name='job',
            name='target_companies_enabled',
            field=models.BooleanField(default=False, help_text='Enable target companies filter'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='required_skills',
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('Important', 'Important'), ('Nice-to-have', 'Nice-to-have')], default='Important', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.skill')),
            ],
            options={
                'ordering': ['priority', 'skill__name'],
                'unique_together': {('job', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ManyToManyField(blank=True, help_text='Required skills with priority', related_name='jobs', through='jobs.JobSkill', to='jobs.skill'),
        ),
    ]
