# Generated by Django 4.2.26 on 2025-11-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_skill_remove_job_demographic_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='age_range_auto_reject',
            field=models.BooleanField(default=False, help_text="Auto reject candidates who don't meet age range requirements"),
        ),
        migrations.AlterField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctorate', 'Doctorate'), ('postdoctoral', 'Postdoctoral'), ('any', 'Any')], help_text='Education level requirement', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='education_level_auto_reject',
            field=models.BooleanField(default=False, help_text="Auto reject candidates who don't meet education level requirement"),
        ),
        migrations.AlterField(
            model_name='job',
            name='education_major_auto_reject',
            field=models.BooleanField(default=False, help_text="Auto reject candidates who don't meet education major requirement"),
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], help_text='Gender requirement', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='gender_auto_reject',
            field=models.BooleanField(default=False, help_text="Auto reject candidates who don't meet gender requirement"),
        ),
        migrations.AlterField(
            model_name='job',
            name='military_auto_reject',
            field=models.BooleanField(default=False, help_text="Auto reject candidates who don't meet military status requirement"),
        ),
        migrations.AlterField(
            model_name='job',
            name='military_status',
            field=models.CharField(blank=True, choices=[('completed_or_full_exempt', 'Completed or Full Exempt'), ('educational_exempt', 'Educational Exempt'), ('any', 'Any')], help_text='Military service status requirement', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='preferred_universities',
            field=models.JSONField(blank=True, default=list, help_text="List of preferred universities (e.g., ['top_iranian', 'international', ...])"),
        ),
        migrations.AlterField(
            model_name='job',
            name='preferred_universities_auto_reject',
            field=models.BooleanField(default=False, help_text="Auto reject candidates who don't meet preferred universities requirement"),
        ),
        migrations.AlterField(
            model_name='job',
            name='preferred_universities_enabled',
            field=models.BooleanField(default=False, help_text='Enable preferred universities requirement'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='required_skills',
        ),
        migrations.AlterField(
            model_name='job',
            name='target_companies',
            field=models.JSONField(blank=True, default=list, help_text='List of target companies'),
        ),
        migrations.AlterField(
            model_name='job',
            name='target_companies_enabled',
            field=models.BooleanField(default=False, help_text='Enable target companies requirement'),
        ),
        migrations.DeleteModel(
            name='JobSkill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text="List of required skills with priority: [{'name': 'Python', 'priority': 'Critical'}, ...]"),
        ),
    ]
