# Generated by Django 4.2.26 on 2025-11-15 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_default_created_by(apps, schema_editor):
    """Set default created_by for any existing jobs with null created_by"""
    Job = apps.get_model('jobs', 'Job')
    User = apps.get_model('core', 'User')
    
    # Get the first user, or create a system user if none exists
    jobs_with_null = Job.objects.filter(created_by__isnull=True)
    if jobs_with_null.exists():
        first_user = User.objects.first()
        if not first_user:
            # Create a system user if no users exist
            first_user = User.objects.create_user(
                email='system@example.com',
                is_active=False
            )
        jobs_with_null.update(created_by=first_user)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_age_range_auto_reject_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_created_by, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(
                help_text='User who created this job',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='created_jobs',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
