# Generated by Django 4.2.16 on 2025-11-15 16:58

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20251115_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='auto_reject_rules',
            field=models.JSONField(blank=True, default=jobs.models.default_dict, help_text='Legacy: Rules for auto-rejecting candidates. Use demographic_requirements instead.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='education_major',
            field=models.JSONField(blank=True, default=jobs.models.default_list, help_text='List of required education majors'),
        ),
        migrations.AlterField(
            model_name='job',
            name='preferred_universities',
            field=models.JSONField(blank=True, default=jobs.models.default_list, help_text="List of preferred universities (e.g., ['top_iranian', 'international', ...])"),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.JSONField(blank=True, default=jobs.models.default_list, help_text="List of required skills with priority: [{'name': 'Python', 'priority': 'Critical'}, ...]"),
        ),
        migrations.AlterField(
            model_name='job',
            name='target_companies',
            field=models.JSONField(blank=True, default=jobs.models.default_list, help_text='List of target companies'),
        ),
    ]
